"""Per-session execution plans generated by a plan-role backend.

The plan is produced once for a session, cached by session key, and injected at
the end of the system prompt. Injection position is stable; the status line is
compact so the executor has a visible rail without a large per-turn scaffold.
"""

from __future__ import annotations

from dataclasses import replace

from harness.backends.pool import BackendPool, PooledBackend
from harness.config import Settings
from harness.ir import Conversation, TextDelta, TextPart, ToolCallPart

HEADER = "## Execution plan"


class PlanningManager:
    def __init__(self, settings: Settings) -> None:
        self.cfg = settings.planning
        self.plans: dict[str, tuple[str, ...]] = {}

    def inject(self, key: str, conv: Conversation) -> Conversation:
        steps = self.plans.get(key)
        if not self.cfg.enabled or not steps or HEADER in conv.system:
            return conv
        block = "\n".join(f"{i + 1}. {s}" for i, s in enumerate(steps))
        status = _status_line(steps, conv)
        return replace(conv, system=f"{conv.system}\n\n{HEADER}\n{block}\n{status}")

    async def ensure(
        self, key: str, conv: Conversation, pool: BackendPool, metrics: dict
    ) -> None:
        if not self.cfg.enabled or key in self.plans:
            return
        backend = _planner_backend(pool)
        prompt = _planning_prompt(conv, self.cfg.max_chars)
        payload = {
            "model": backend.model_name,
            "messages": [
                {"role": "system", "content": _planner_system(self.cfg.max_steps)},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": min(800, self.cfg.max_chars),
            "stream": True,
            "stream_options": {"include_usage": True},
        }
        text = ""
        async for ev in backend.profile.parse(backend.stream(payload)):
            if isinstance(ev, TextDelta):
                text += ev.text
        steps = _parse_steps(text, self.cfg.max_steps)
        if not steps:
            steps = ("Restate the task, inspect relevant files, make the change, verify it.",)
        self.plans[key] = steps
        metrics["plan_steps"] = len(steps)
        metrics["plan_generated"] = 1


def _planner_backend(pool: BackendPool) -> PooledBackend:
    candidates = pool.with_role("plan") or pool.with_role("main") or pool.backends
    return min(candidates, key=lambda b: (b.in_flight, b.requests))


def _planner_system(max_steps: int) -> str:
    return (
        "Write a concrete execution plan for a coding agent. "
        f"Return at most {max_steps} numbered steps. "
        "Each step must be imperative, specific, and short. Return only the plan."
    )


def _planning_prompt(conv: Conversation, max_chars: int) -> str:
    texts: list[str] = []
    if conv.system:
        texts.append(conv.system[: max_chars // 2])
    for turn in conv.turns:
        for part in turn.parts:
            if isinstance(part, TextPart):
                texts.append(part.text)
    return "\n\n".join(texts)[-max_chars:]


def _parse_steps(text: str, max_steps: int) -> tuple[str, ...]:
    steps: list[str] = []
    for raw in text.splitlines():
        line = raw.strip(" -\t")
        if not line:
            continue
        if "." in line and line.split(".", 1)[0].isdigit():
            line = line.split(".", 1)[1].strip()
        if line:
            steps.append(line[:160])
        if len(steps) >= max_steps:
            break
    return tuple(steps)


def _status_line(steps: tuple[str, ...], conv: Conversation) -> str:
    calls = sum(
        1 for turn in conv.turns for part in turn.parts if isinstance(part, ToolCallPart)
    )
    current = min(calls + 1, len(steps))
    done = "none" if calls == 0 else " ".join(f"{i}✓" for i in range(1, current))
    return f"Plan status: Step {current}/{len(steps)}: {steps[current - 1]}; done: {done}"


def plan_status(system: str) -> tuple[int, int, str] | None:
    import re

    match = re.search(r"Plan status: Step (\d+)/(\d+): ([^;\n]+)", system)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2)), match.group(3)
